# yaml-language-server: $schema=https://raw.githubusercontent.com/koder-cat/k8s-ephemeral-environments/main/.github/actions/validate-config/schema.json

projectId: todo-app
trigger: on-demand

app:
  port: 3000
  healthPath: /api/health

image:
  context: ./todo-app
  dockerfile: Dockerfile

databases:
  postgresql: true
